-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.book
(
    title character varying NOT NULL,
    isbn bigint NOT NULL,
    authors character varying[] NOT NULL,
    synopsis character varying,
    publisher character varying[],
    publication_date date,
    print_version boolean NOT NULL,
    genre character varying[] NOT NULL,
    language character varying[] NOT NULL,
    "average rating" double precision NOT NULL DEFAULT 0,
    quantity bigint NOT NULL DEFAULT 0,
    price double precision NOT NULL DEFAULT 0,
    PRIMARY KEY (isbn)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    email character varying,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    phone_number character varying NOT NULL,
    PRIMARY KEY (email),
    UNIQUE (phone_number)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    "employeeID" bigserial,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    phone_number bigint NOT NULL,
    email character varying NOT NULL,
    PRIMARY KEY ("employeeID"),
    UNIQUE (phone_number, email)
);

CREATE TABLE IF NOT EXISTS public.purchases
(
    book_isbn bigint NOT NULL,
    customer_email character varying NOT NULL,
    purchase_timestamp timestamp with time zone NOT NULL,
    PRIMARY KEY (book_isbn, customer_email, purchase_timestamp)
);

ALTER TABLE IF EXISTS public.purchases
    ADD FOREIGN KEY (book_isbn)
    REFERENCES public.book (isbn) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.purchases
    ADD FOREIGN KEY (customer_email)
    REFERENCES public.customer (email) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
